#!/usr/bin/env bash
#This is question for 6-superstitious_numbers
count=1
while [[ $count -le 20 ]]; do
	echo $count
	case $count in
	4)
		echo "bad luck from China"
		;;
	5)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
	
	
	esac
	((count++))
done
